/***********************************************************/
/* Version 2.30.00                                         */
/***********************************************************/
#ifndef _TMS320
#define _TMS320
 
typedef unsigned int   uint;
typedef unsigned short ushort;  
#define PASS -1


  typedef short DATA;
  typedef long LDATA;
  #define ABSVAL abs
  #define SHIFT15 >>15
  #define SHIFT1  /2
  #define ROUND 0x400
  #define DIV2	>>1

#endif
