all:
	gcc main.c -o main -g
	gcc writer_odd.c -o writer_odd -g
	gcc reader_odd.c -o reader_odd -g
	gcc writer_even.c -o writer_even -g
	gcc reader_even.c -o reader_even -g
clean:
	rm main writer_odd reader_odd writer_even reader_even
